### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by pftbest** [ajxs/atom-make#1]
[Enter steps to reproduce below:]

1. ... Pressed Ctrl+F6
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-make](https://github.com/ajxs/atom-make) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/vadzim/.atom/packages/atom-make/atom-make.js:14

TypeError: Cannot read property 'buffer' of undefined
    at Object.execProcess (/Users/vadzim/.atom/packages/atom-make/atom-make.js:14:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:1104:28)
    at EventEmitter.outerCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -4:27.6.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  4x -4:20.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:19.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:16.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:39.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:20.5.0 git-plus:add-all (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:10.5.0 grammar-selector:show (atom-text-editor.editor)
  3x -0:29 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.5.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.0 atom-make:clean (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/vadzim/gopath/src"
  }
}
```

### Installed Packages

```coffee
# User
atom-make, v0.4.0 (inactive)
autocomplete-clang, v0.9.3 (active)
autocomplete-go, v1.1.0 (active)
builder-go, v1.0.0 (active)
clang-format, v1.25.0 (active)
git-plus, v5.14.0 (active)
go-config, v1.1.4 (active)
go-get, v1.0.3 (active)
go-plus, v4.1.0 (active)
gofmt, v1.1.6 (active)
gometalinter-linter, v1.1.0 (active)
gorename, v1.0.2 (active)
language-diff, v0.4.0 (active)
language-patch, v1.0.0 (active)
linter, v1.11.8 (active)
linter-clang, v3.4.4 (active)
navigator-godef, v1.0.3 (active)
tester-go, v1.0.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ajxs** [comment]
Thanks for reporting this! 
I was able to reproduce this, by running the commands without having an active pane. It makes sense why this would happen, since this scenario isn't handled in the code.
Tonight or tomorrow I'll release a fix for it which handles this scenario! Thanks for pointing this out!

**Comment by pftbest** [comment]
Thank you for making this plugin!

**Comment by ajxs** [comment]
Latest commit implements some limited error handling which should solve this issue. 
Another issue remains which I'll be looking into over the next few days.
